name: Build and deploy Python app to Azure Web App - analytixnexa

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python version
        uses: actions/setup-python@v2
        with:
          python-version: "3.12" # Updated to a stable Python version

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: 'Store env values'
        run: |
          echo "${{ secrets.AUTH_PROVIDER_X509_CERT_URL }}" > .env
          echo "${{ secrets.CLIENT_EMAIL}}" > .env
          echo "${{ secrets.CLIENT_ID }}" > .env
          echo "${{ secrets.CLIENT_PROVIDER_X509_CERT_URL }}" > .env
          echo "${{ secrets.PRIVATE_KEY }}" > .env
          echo "${{ secrets.PRIVATE_KEY_ID }}" > .env
        env: |
          AUTH_PROVIDER_X509_CERT_URL="${{ secrets.AUTH_PROVIDER_X509_CERT_URL }}"
          CLIENT_EMAIL="${{ secrets.CLIENT_EMAIL}}"

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v2
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip -o release.zip

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v2
        with:
          app-name: "analytixnexa"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_432B265E900D4AF088A5DAF47956F2E4 }}
